name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64]
        include:
          - arch: x64
            python-arch: x64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.7'
        architecture: ${{ matrix.python-arch }}

    - name: Download FFmpeg
      run: |
        # Create tools directory
        mkdir -p tools
        
        # Download FFmpeg
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -OutFile "tools\ffmpeg.zip"
        
        # Extract FFmpeg
        Expand-Archive -Path "tools\ffmpeg.zip" -DestinationPath "tools\ffmpeg"
        
        # Move binaries to tools directory
        Move-Item -Path "tools\ffmpeg\ffmpeg-master-latest-win64-gpl\bin\*" -Destination "tools"
        
        # Clean up
        Remove-Item -Path "tools\ffmpeg" -Recurse
        Remove-Item -Path "tools\ffmpeg.zip"
        
        # Add to PATH
        echo "${{ github.workspace }}\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Build executable
      run: |
        # Copy FFmpeg to dist directory for bundling
        python setup_windows.py
        Copy-Item -Path "tools\ffmpeg.exe" -Destination "dist"
        Copy-Item -Path "tools\ffprobe.exe" -Destination "dist"

    - name: Create ZIP archive
      run: |
        cd dist
        7z a ../MusicDownloader-win64.zip MusicDownloader.exe ffmpeg.exe ffprobe.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MusicDownloader-win64
        path: MusicDownloader-win64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: MusicDownloader-win64.zip
        generate_release_notes: true
        draft: true
        prerelease: true
        discussion_category_name: Releases
        body: |
          ⚠️ **This is a pre-release version and may be unstable!**
          
          ## Installation
          1. Download the zip file for your system
          2. Extract all contents to the same directory
          3. Run `MusicDownloader.exe` (requires admin rights)
          
          ## Requirements
          - Windows 10 or later (64-bit)
          - No additional downloads needed - FFmpeg is included!
          
          ## Known Issues
          - USB detection can be flaky
          - Sometimes crashes for no apparent reason
          - Progress bars occasionally get stuck
          
          Please report any bugs you find! 